services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/concord
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      MONGODB_URL: mongodb://mongo:27017/concord
      SPRING_PROFILES_ACTIVE: local

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: concord
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/mongo/data

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/redis/data

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  redis_data:
    driver: local
